security:
          
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER : ROLE_USER
        ROLE_CONTROLLER: [ROLE_USER,ROLE_CONTROLLER]
        ROLE_GLOBAL_CONTROLLER: [ROLE_CONTROLLER,ROLE_GLOBAL_CONTROLLER]
        ROLE_ACCOUNT_MANAGER: [ROLE_GLOBAL_CONTROLLER,ROLE_ACCOUNT_MANAGER]
        ROLE_ADMIN:       [ROLE_ACCOUNT_MANAGER,ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      fos_userbundle:
            id: fos_user.user_provider.username
      
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
      main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       
               path: fos_user_security_logout
               target: /
            anonymous:    true
      
        #dev:
            #pattern:  ^/(_(profiler|wdt)|css|images|js)/
            #security: false

        #login:
            #pattern:  ^/demo/secured/login$
            #security: false

        #secured_area:
            #pattern:    ^/demo/secured/
            #form_login:
                #check_path: _security_check
                #login_path: _demo_login
            #logout:
                #path:   _demo_logout
                #target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/, role: ROLE_ADMIN }
        - { path: ^/chartofaccountsedit, role: ROLE_ACCOUNT_MANAGER}
        - { path: ^/usermanager, role: ROLE_ACCOUNT_MANAGER}


